import type { SetCommentaryOptions } from './setCommentaryLibrary';

export const WEIGHT_DECREASE_MET: SetCommentaryOptions = {
  shortMessages: [
    'Adjusted Well',
    'Right Call',
    'Smart Drop',
    'Recovery Focus',
    'Good Reset',
    'Handled It',
    'Controlled Cut',
    'Back on Track',
    'Balance Restored',
    'Fatigue Managed',
    'Right Adjustment',
    'Smart Reset',
  ] as const,
  tooltips: [
    '{reps} reps after drop',
    'Weight drop met: {reps}',
    'Adjustment worked: {reps}',
    'Smart drop: {reps}',
    'Recovered reps: {reps}',
    'Reset success: {reps}',
    'Drop paid off: {reps}',
    'Good call: {reps}',
    'Recovery set: {reps}',
    'Managed well: {reps}',
  ] as const,
  whyLines: [
    'Drop let you recover',
    'Good call adjusting',
    'Energy restored',
    'Fatigue managed well',
    'Technique held steady',
    'Reset helped performance',
    'Smarter pacing',
    'Right adjustment',
    'Momentum rebuilt',
    'Strength stabilized',
    'Managed fatigue',
    'Recovery effective',
  ] as const,
};

export const WEIGHT_DECREASE_SLIGHTLY_BELOW: SetCommentaryOptions = {
  shortMessages: [
    'Still Heavy',
    'Not Quite',
    'Needs More Drop',
    'Close',
    'Almost Recovered',
    'Slightly Low',
    'Not Fully Reset',
    'Still Struggling',
    'Near Recovery',
    'Almost There',
    'Needs More Rest',
    'Partial Reset',
  ] as const,
  tooltips: [
    '{reps} reps after drop',
    'Still short: {reps}',
    'Not enough: {reps}',
    'Close but low: {reps}',
    'Recovery not full: {reps}',
    'Drop insufficient: {reps}',
    'Almost recovered: {reps}',
    'Still heavy: {reps}',
    'Partial reset: {reps}',
    'Need more drop',
  ] as const,
  whyLines: [
    'Fatigue still high',
    'Drop not enough',
    'Recovery incomplete',
    'Strength still down',
    'Need more rest',
    'Energy still low',
    'Adjustment insufficient',
    'Consider larger drop',
    'Still fatigued',
    'Body not fully recovered',
    'Reset partially worked',
    'Strength not back yet',
  ] as const,
  improveLines: [
    'Drop weight a bit more',
    'Add extra rest before this set',
    'Keep this load and aim to match reps on the next set',
    'Tighten setup and tempo to stabilize performance',
    'Stop 1 rep before form breakdown to keep quality high',
  ] as const,
};

export const WEIGHT_DECREASE_SIGNIFICANTLY_BELOW: SetCommentaryOptions = {
  shortMessages: [
    'Fatigue High',
    'Drop Not Enough',
    'Still Heavy',
    'Needs More Reset',
    'Overworked',
    'Big Fatigue',
    'Recovery Needed',
    'Strength Down',
    'Heavy Burn',
    'Too Taxing',
    'Needs Break',
    'Deep Fatigue',
  ] as const,
  tooltips: [
    '{reps} reps after drop',
    'Still too heavy: {reps}',
    'Fatigue high: {reps}',
    'Drop not enough: {reps}',
    'Major fatigue: {reps}',
    'Not recovered: {reps}',
    'Needs more drop',
    'Too taxing: {reps}',
    'Still heavy load',
    'Strength down',
  ] as const,
  whyLines: [
    'Fatigue still very high',
    'Recovery insufficient',
    'Drop was too small',
    'Strength significantly down',
    'Body needs more rest',
    'Set-to-set fatigue is limiting output right now',
    'Energy depleted',
    'Possible overreach',
    'Need deeper reset',
    'You likely need a deeper in-session reset',
    'Systemic fatigue present',
    'Training stress high',
  ] as const,
  improveLines: [
    'Reduce load further',
    'Take longer rest before repeating this effort',
    'Use controlled reps and keep form strict',
    'Treat the next set as a quality set, not an all-out set',
    'Rebuild reps gradually before increasing intensity again',
  ] as const,
};
