import type { SetCommentaryOptions } from './setCommentaryLibrary';

export const SAME_WEIGHT_REPS_INCREASED: SetCommentaryOptions = {
  shortMessages: [
    'Second Wind',
    'Rallying',
    'Reserves Found',
    'Recovery Win',
    'Energy Boost',
    'Comeback',
    'Back on Track',
    'Bounce Back',
    'Momentum Shift',
    'Fresh Energy',
    'Rising Again',
    'Better Rest Paid Off',
  ] as const,
  tooltips: [
    '+{diff} reps vs last',
    'Found {diff} more reps',
    'Recovery helped - +{diff}',
    '+{diff} reps: reserves found',
    'Bounced back +{diff} reps',
    'Energy returned: +{diff}',
    'Better pacing: +{diff}',
    'Rest time helped +{diff}',
    'Momentum shifting +{diff}',
    'Reserves available +{diff}',
  ] as const,
  whyLines: [
    'Had reserves in last set',
    'Or took longer rest this time',
    'Better recovery between sets',
    'Pacing improved across sets',
    'Found energy reserves',
    'Recovery was effective',
    'Fatigue managed well',
    'Rest time paid dividends',
    'Body adapted to workload',
    'Neural system recovered',
    'Energy levels rebounded',
    'Better breathing technique',
  ] as const,
  improveLines: [
    'Keep longer rests to sustain',
    'You have more in the tank',
    'Push even harder next time',
    'Maintain this energy level',
  ] as const,
};

export const SAME_WEIGHT_REPS_SAME: SetCommentaryOptions = {
  shortMessages: [
    'Consistent',
    'Steady',
    'Locked In',
    'Solid',
    'On Point',
    'Rock Solid',
    'Controlled',
    'Perfect Pace',
    'Even Output',
    'Measured',
    'Stable',
    'Precision Work',
  ] as const,
  tooltips: [
    'Maintained {reps} reps',
    'Steady: {reps} reps',
    'Locked at {reps} reps',
    'Rock solid: {reps} reps',
    'Perfect pacing: {reps}',
    'Even output: {reps} reps',
    'Controlled: {reps} reps',
    'On point: {reps} reps',
    'Consistent: {reps} reps',
    'Measured: {reps} reps',
  ] as const,
  whyLines: [
    'Good pacing and recovery',
    'Rest time is working well',
    'Fatigue managed perfectly',
    'Pacing was on point',
    'Recovery between sets solid',
    'Energy levels stable',
    'Technique remained consistent',
    'Breathing was steady',
    'Focus maintained well',
    'Workload distributed evenly',
    'Rest periods optimal',
    'Neural system firing consistently',
  ] as const,
  improveLines: [
    'Try to push for more reps',
    'Increase weight slightly',
    'Add one more rep next time',
    'You could go harder',
  ] as const,
};

export const SAME_WEIGHT_DROP_MILD: SetCommentaryOptions = {
  shortMessages: [
    'Normal Fatigue',
    'Expected Drop',
    'Standard Fatigue',
    'Natural Decline',
    'Normal Pattern',
    'Typical Fatigue',
    'Working Hard',
    'Expected',
    'On Track',
    'Normal Course',
    'Fatigue Setting In',
    'Working as Expected',
  ] as const,
  tooltips: [
    '-{dropAbs} reps ({dropPct}%)',
    '-{dropAbs} reps: normal',
    '-{dropAbs} reps: expected',
    '-{dropAbs}: standard fatigue',
    '-{dropAbs} reps typical',
    'Normal: -{dropAbs} reps',
    '-{dropAbs} expected drop',
    '-{dropAbs} reps: natural',
    '-{dropAbs}: working hard',
    '-{dropAbs} reps: expected',
  ] as const,
  whyLines: [
    'Normal fatigue pattern',
    'Expected decline over sets',
    'Standard endurance limits',
    'This is typical drop-off',
    'Fatigue buildup is normal',
    'Working within normal range',
    'Pacing consistent',
    'Effort level appropriate',
    'Expected energy drop',
    'Normal set-to-set decline',
    'Work capacity holding',
    'Strength curve normal',
  ] as const,
  improveLines: [
    'Extend rest by 30 seconds',
    'Pace slower on first sets',
    'Focus on breathing between sets',
  ] as const,
};

export const SAME_WEIGHT_DROP_MODERATE: SetCommentaryOptions = {
  shortMessages: [
    'Fatigue Build',
    'Energy Dip',
    'Slight Drop',
    'Working Hard',
    'Form Holding',
    'Tiring Out',
    'Normal Fatigue',
    'Energy Fading',
    'Still Strong',
    'Grinding',
    'Fatigue Noticeable',
    'Digging Deep',
  ] as const,
  tooltips: [
    '-{dropAbs} reps ({dropPct}%)',
    '-{dropAbs} reps: fatigue',
    '-{dropAbs} reps: effort rising',
    '-{dropAbs}: holding on',
    '-{dropAbs} reps: still solid',
    '-{dropAbs} reps: tiring',
    '-{dropAbs}: fatigue building',
    '-{dropAbs} reps: expected',
    '-{dropAbs}: keep pushing',
    '-{dropAbs} reps: working',
  ] as const,
  whyLines: [
    'Fatigue building up',
    'Energy reserves dropping',
    'Effort rising each set',
    'Still within normal range',
    'Work capacity challenged',
    'Pacing could be tighter',
    'Rest might need adjustment',
    'Strength curve declining',
    'Muscle endurance taxed',
    'Energy management needed',
    'Form still holding',
    'Push through fatigue',
  ] as const,
  improveLines: [
    'Take longer rest between sets',
    'Keep the same load and aim to lose fewer reps next set',
    'Use steadier tempo to preserve output',
    'Set up breathing before each rep to improve endurance',
  ] as const,
};

export const SAME_WEIGHT_DROP_SEVERE: SetCommentaryOptions = {
  shortMessages: [
    'Fatigue Spike',
    'Big Drop',
    'Energy Crash',
    'Deep Fatigue',
    'Recovery Needed',
    'Overreached',
    'Tank Empty',
    'Major Dip',
    'Energy Drained',
    'Needs Rest',
    'Fatigue Hit Hard',
    'Time to Recover',
  ] as const,
  tooltips: [
    '-{dropAbs} reps ({dropPct}%)',
    '-{dropAbs} reps: big drop',
    '-{dropAbs}: fatigue spike',
    '-{dropAbs} reps: heavy fatigue',
    '-{dropAbs}: needs recovery',
    '-{dropAbs} reps: deep fatigue',
    '-{dropAbs}: energy crash',
    '-{dropAbs} reps: tank empty',
    '-{dropAbs}: hard drop',
    '-{dropAbs} reps: too steep',
  ] as const,
  whyLines: [
    'Fatigue accumulated quickly',
    'Energy reserves depleted',
    'Recovery may be needed',
    'Rest time too short',
    'Set intensity too high',
    'Endurance limit reached',
    'Consider longer rest',
    'Energy management needed',
    'Fatigue hit hard',
    'Potential overreach',
    'Recovery signals present',
    'Body asking for rest',
  ] as const,
  improveLines: [
    'Add more rest before the hard sets',
    'Use a slightly lighter load for this exercise',
    'Prioritize clean reps and stop 1 rep before form breaks',
    'Push to failure on your last set',
  ] as const,
};
