import type { SetCommentaryOptions } from './setCommentaryLibrary';

export const WEIGHT_INCREASE_EXCEEDED: SetCommentaryOptions = {
  shortMessages: [
    'Crushed It',
    'Overdelivered',
    'Exceeded',
    'Stronger Than Expected',
    'Surplus Strength',
    'Beyond Target',
    'More in the Tank',
    'Handled With Ease',
    'Cleared the Bar',
    'Weight Conquered',
    'Better Than Plan',
    'Outperformed',
  ] as const,
  tooltips: [
    '{reps} reps at +{weight}kg',
    'Exceeded goal: {reps} reps',
    'More than planned: {reps}',
    'Stronger: {reps} reps',
    'Over target: {reps}',
    '{reps} reps, goal surpassed',
    'Weight too easy: {reps}',
    'Cleared target by {reps}',
    'Extra reps: {reps}',
    'Beyond plan: {reps}',
  ] as const,
  whyLines: [
    'Strength up noticeably',
    'Weight was too light',
    'Recovery was strong',
    'Adaptation kicked in',
    'Power output increased',
    'Progress exceeded expectations',
    'This weight is now comfortable',
    'Time to move up',
    'Form held easily',
    'Energy reserves high',
    'Strength surplus evident',
    'Performance over target',
  ] as const,
};

export const WEIGHT_INCREASE_MET: SetCommentaryOptions = {
  shortMessages: [
    'Goal Met',
    'Right on Target',
    'On Plan',
    'Perfect Match',
    'Target Hit',
    'Right There',
    'As Planned',
    'Nailed It',
    'Exact Match',
    'Plan Delivered',
    'Executed',
    'On the Dot',
  ] as const,
  tooltips: [
    '{reps} reps at +{weight}kg',
    'Target hit: {reps} reps',
    'As planned: {reps} reps',
    'Goal met: {reps} reps',
    '{reps} reps on plan',
    'Perfect execution: {reps}',
    'Right at goal: {reps}',
    'Exact target: {reps}',
    'Matched plan: {reps}',
    'Weight increase met',
  ] as const,
  whyLines: [
    'Progress on track',
    'Strength matched plan',
    'Good execution',
    'Appropriate weight jump',
    'Recovery supported progress',
    'Plan pacing is right',
    'Strength adapting well',
    'Consistent performance',
    'Target load achieved',
    'Progression working',
    'Performance aligned',
    'Plan delivered as expected',
  ] as const,
};

export const WEIGHT_INCREASE_SLIGHTLY_BELOW: SetCommentaryOptions = {
  shortMessages: [
    'Close Call',
    'Nearly There',
    'Just Missed',
    'Slightly Below',
    'Almost Hit',
    'Near Target',
    'Right Behind',
    'One Rep Short',
    'Borderline',
    'Almost On Plan',
    'Slightly Off',
    'Just Under',
  ] as const,
  tooltips: [
    '{reps} reps (target {target})',
    'Just short: {reps} reps',
    'Near target: {reps}',
    'Almost hit: {reps}',
    '{reps} reps, close',
    'Slightly under: {reps}',
    'Close call: {reps}',
    'One rep off: {reps}',
    'Borderline: {reps}',
    'Near goal: {reps}',
  ] as const,
  whyLines: [
    'Small gap to target',
    'Strength is almost there',
    'Recovery slightly off',
    'Energy dipped near end',
    'Close to plan',
    'Minor adjustment needed',
    'Almost ready to progress',
    'Need a touch more rest',
    'Just a bit more strength',
    'Nearly on track',
    'Fatigue limited last rep',
    'Close but not quite',
  ] as const,
  improveLines: [
    'Add a little more rest',
    'Keep the weight and aim to hit target next time',
    'Focus on clean reps',
    'Increase recovery before this set',
    'Slight bump in sleep could help',
  ] as const,
};

export const WEIGHT_INCREASE_SIGNIFICANTLY_BELOW: SetCommentaryOptions = {
  shortMessages: [
    'Too Heavy',
    'Overreached',
    'Big Drop',
    'Missed Target',
    'Load Too High',
    'Needs Adjustment',
    'Not There Yet',
    'Underperformed',
    'Weight Jump Too Big',
    'Recovery Needed',
    'Performance Dip',
    'Step Back Needed',
  ] as const,
  tooltips: [
    '{reps} reps (target {target})',
    'Below target: {reps}',
    'Missed by a lot: {reps}',
    'Too heavy: {reps}',
    'Significantly under: {reps}',
    'Load too high: {reps}',
    'Big miss: {reps}',
    'Not ready: {reps}',
    'Drop in reps: {reps}',
    'Weight jump too much',
  ] as const,
  whyLines: [
    'Weight increase too aggressive',
    'Strength not ready for jump',
    'Recovery insufficient',
    'Energy was low',
    'Fatigue too high',
    'Load exceeded capacity',
    'Need smaller increment',
    'Overreached slightly',
    'Muscle endurance limited',
    'Progression needs adjustment',
    'Strength gap remains',
    'Current jump overshot your working capacity',
  ] as const,
  improveLines: [
    'Use a smaller jump on the next attempt',
    'Keep this load only if reps recover quickly in the next set',
    'Take more rest before your top set',
    'Build reps at a slightly lower load before pushing up again',
    'Focus on setup and bar path to avoid early fatigue',
  ] as const,
};
